import { logInfo, logError } from '../core/logging';

/**
 * AssetSearchService is responsible for finding visual assets (images/videos)
 * based on the descriptive "visualPrompt" keywords generated by the AI.
 */
export class AssetSearchService {
  /**
   * Searches for a relevant asset URL.
   * In a real implementation, this would call Pexels, Unsplash, or Pixabay APIs.
   */
  public async findAsset(keywords: string): Promise<string> {
    logInfo('Searching for visual asset.', { phase: 'asset_search', keywords });

    try {
      // Simulate API call to a stock provider
      await new Promise((resolve) => setTimeout(resolve, 500));

      // Mocked logic: If keywords include 'lion', return a lion image, etc.
      const normalized = keywords.toLowerCase();
      
      if (normalized.includes('lion')) {
        return 'https://images.unsplash.com/photo-1614027126733-757680ce22f9?auto=format&fit=crop&w=1080&q=80';
      }
      
      if (normalized.includes('eagle')) {
        return 'https://images.unsplash.com/photo-1506220926022-cc2c17377c16?auto=format&fit=crop&w=1080&q=80';
      }

      if (normalized.includes('space') || normalized.includes('galaxy')) {
        return 'https://images.unsplash.com/photo-1462331940025-496df975641f?auto=format&fit=crop&w=1080&q=80';
      }

      // Default fallback: A nice abstract background based on the keywords
      const encoded = encodeURIComponent(keywords.substring(0, 50));
      return `https://placehold.co/1080x1920/222/ddd/png?text=${encoded}`;
      
    } catch (error: any) {
      logError('Asset search failed, using default placeholder.', { errorMessage: error.message });
      return 'https://placehold.co/1080x1920/000/fff/png?text=Fallback+Asset';
    }
  }
}
